name: Trigger auto deployment for ayu-order

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'productCheckoutManagement/**'
    - '.github/workflows/ayu-order-AutoDeployTrigger-90f8f038-828b-45a2-880f-ed3db197082a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
      
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: productCheckoutManagement
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AYUORDER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AYUORDER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AYUORDER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/productCheckoutManagement 
          registryUrl: ayulanka.azurecr.io
          registryUsername: ${{ secrets.AYUORDER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AYUORDER_REGISTRY_PASSWORD }}
          containerAppName: ayu-order
          resourceGroup: CTSE_Assignment
          imageToBuild: ayulanka.azurecr.io/ayu-order:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


